services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sofka-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.4
    container_name: customer-db
    environment:
      MYSQL_DATABASE: customer_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-service:
    build:
      context: .
    container_name: customer-service
    depends_on:
      rabbitmq:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/customer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

volumes:
  mysql_data:
